package syntax

const sqlKeywords = `SELECT FROM WHERE AND OR NOT IN IS NULL LIKE ILIKE BETWEEN EXISTS INSERT INTO VALUES UPDATE SET DELETE
CREATE TABLE VIEW INDEX DROP ALTER ADD COLUMN PRIMARY KEY FOREIGN REFERENCES UNIQUE DEFAULT CHECK CONSTRAINT
JOIN INNER LEFT RIGHT FULL OUTER CROSS ON USING GROUP BY ORDER HAVING LIMIT OFFSET ASC DESC DISTINCT AS
UNION ALL INTERSECT EXCEPT CASE WHEN THEN ELSE END BEGIN COMMIT ROLLBACK TRANSACTION WITH RECURSIVE RETURNING
EXPLAIN ANALYZE SHOW DESCRIBE USE DATABASE SCHEMA DATABASES TABLES IF TRUE FALSE CAST INTERVAL PRAGMA VACUUM
AUTO_INCREMENT AUTOINCREMENT SERIAL INTEGER INT BIGINT TEXT VARCHAR BOOLEAN JSON JSONB TIMESTAMP DATE REAL NUMERIC DECIMAL`

const sqlFunctions = `COUNT SUM AVG MIN MAX COALESCE NULLIF NOW LOWER UPPER LENGTH SUBSTRING TRIM ROUND ABS
JSON_EXTRACT JSON_OBJECT JSON_ARRAY JSONB_PRETTY JSON_AGG JSONB_AGG TO_JSON ROW_NUMBER RANK DENSE_RANK
DATE_TRUNC EXTRACT CONCAT GROUP_CONCAT STRING_AGG ARRAY_AGG DATETIME STRFTIME`

const cqlKeywords = `SELECT FROM WHERE AND IN INSERT INTO VALUES UPDATE SET DELETE CREATE KEYSPACE TABLE DROP ALTER
PRIMARY KEY WITH CLUSTERING ORDER BY ASC DESC LIMIT ALLOW FILTERING USE IF NOT EXISTS TRUNCATE BATCH APPLY
BEGIN TTL TIMESTAMP USING DESCRIBE KEYSPACES TABLES INDEX MATERIALIZED VIEW TYPE REPLICATION DISTINCT JSON
TEXT INT BIGINT UUID TIMEUUID BOOLEAN DOUBLE FLOAT MAP SET LIST FROZEN COUNTER BLOB TOKEN CONTAINS`

const cqlFunctions = `COUNT NOW TOTIMESTAMP TODATE WRITETIME TTL UUID MINTIMEUUID MAXTIMEUUID TOJSON FROMJSON SUM AVG MIN MAX`

const redisCommands = `GET SET SETEX SETNX MGET MSET DEL EXISTS EXPIRE TTL PTTL PERSIST TYPE KEYS SCAN RENAME INCR INCRBY DECR APPEND STRLEN
HGET HSET HMGET HGETALL HDEL HKEYS HVALS HLEN HEXISTS HINCRBY HSCAN
LPUSH RPUSH LPOP RPOP LRANGE LLEN LINDEX LREM LTRIM
SADD SREM SMEMBERS SISMEMBER SCARD SINTER SUNION SDIFF SSCAN
ZADD ZREM ZRANGE ZREVRANGE ZRANGEBYSCORE ZSCORE ZCARD ZINCRBY ZRANK ZSCAN
XADD XRANGE XREVRANGE XLEN XREAD XINFO PUBLISH
INFO PING ECHO DBSIZE SELECT FLUSHDB CONFIG CLIENT COMMAND MEMORY SLOWLOG TIME OBJECT DUMP
JSON.GET JSON.SET JSON.DEL JSON.TYPE JSON.MGET`

const logqlKeywords = `BY WITHOUT ON IGNORING GROUP_LEFT GROUP_RIGHT AND OR UNLESS BOOL
JSON LOGFMT REGEXP PATTERN UNPACK LINE_FORMAT LABEL_FORMAT UNWRAP DROP KEEP DECOLORIZE OFFSET
LABELS VALUES ALL :RANGE :LIMIT`

const logqlFunctions = `RATE COUNT_OVER_TIME BYTES_RATE BYTES_OVER_TIME SUM_OVER_TIME AVG_OVER_TIME MAX_OVER_TIME MIN_OVER_TIME
QUANTILE_OVER_TIME FIRST_OVER_TIME LAST_OVER_TIME ABSENT_OVER_TIME SUM AVG MIN MAX COUNT TOPK BOTTOMK STDDEV SORT SORT_DESC`

const promqlKeywords = `BY WITHOUT ON IGNORING GROUP_LEFT GROUP_RIGHT AND OR UNLESS BOOL OFFSET
METRICS TARGETS ALERTS RULES LABELS VALUES ALL :RANGE :STEP`

const promqlFunctions = `RATE IRATE INCREASE DELTA IDELTA DERIV SUM AVG MIN MAX COUNT TOPK BOTTOMK QUANTILE STDDEV STDVAR COUNT_VALUES GROUP
HISTOGRAM_QUANTILE ABSENT ABSENT_OVER_TIME AVG_OVER_TIME SUM_OVER_TIME MAX_OVER_TIME MIN_OVER_TIME COUNT_OVER_TIME LAST_OVER_TIME
QUANTILE_OVER_TIME PREDICT_LINEAR CLAMP CLAMP_MIN CLAMP_MAX ROUND ABS CEIL FLOOR LABEL_REPLACE LABEL_JOIN SORT SORT_DESC TIME TIMESTAMP VECTOR SCALAR CHANGES RESETS`

const grafanaCommands = `ALL HEALTH SEARCH DASHBOARD DATASOURCES DATASOURCE FOLDERS ALERTS ANNOTATIONS QUERY GET ORG USERS`

var SQL = Language{
	Name:         "sql",
	Keywords:     words(sqlKeywords),
	Functions:    words(sqlFunctions),
	LineComments: []string{"--", "#"},
	BlockComment: true,
	CaseFold:     true,
	Variables:    true,
	Operators:    []string{"<=", ">=", "<>", "!=", "::", "->>", "->", "||", "=", "<", ">", "+", "-", "*", "/", "%"},
}

var CQL = Language{
	Name:         "cql",
	Keywords:     words(cqlKeywords),
	Functions:    words(cqlFunctions),
	LineComments: []string{"--", "//"},
	BlockComment: true,
	CaseFold:     true,
	Variables:    true,
	Operators:    []string{"<=", ">=", "!=", "=", "<", ">", "+", "-", "*", "/"},
}

var Redis = Language{
	Name:         "redis",
	Keywords:     words(redisCommands),
	Functions:    map[string]bool{},
	LineComments: []string{"#"},
	CaseFold:     true,
	WordRunes:    ":-",
}

var LogQL = Language{
	Name:         "logql",
	Keywords:     words(logqlKeywords),
	Functions:    words(logqlFunctions),
	LineComments: []string{"#"},
	CaseFold:     false,
	WordRunes:    ":",
	Operators:    []string{"|=", "!=", "|~", "!~", "=~", "==", ">=", "<=", "|", "=", ">", "<", "+", "-", "*", "/"},
}

var PromQL = Language{
	Name:         "promql",
	Keywords:     words(promqlKeywords),
	Functions:    words(promqlFunctions),
	LineComments: []string{"#"},
	CaseFold:     false,
	WordRunes:    ":",
	Operators:    []string{"!=", "=~", "!~", "==", ">=", "<=", "=", ">", "<", "+", "-", "*", "/", "%", "^"},
}

var Grafana = Language{
	Name:         "grafana",
	Keywords:     words(grafanaCommands),
	Functions:    map[string]bool{},
	LineComments: []string{"#"},
	CaseFold:     true,
	WordRunes:    "-/",
}
